// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UUID    string `gorm:"column:uuid" json:"uuid"`
	Name    string `gorm:"column:name" json:"name"`
	Age     int64  `gorm:"column:age" json:"age"`
	Version int64  `gorm:"column:version" json:"version"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
